# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pr:
  - master

jobs:
 - job: test_Job
   pool:
      name: begonaDev
   steps:
    - task: UseDotNet@2
      displayName: "Use .Net Core 2.1.700"
      inputs:
        version: 2.1.700

    # Build backend
    - task: DotNetCoreCLI@2
      displayName: "build project"
      inputs:
        command: build
        publishWebProjects: false
        projects: "**/*.build-cache-demo.csproj"
        arguments: "--configuration $(Configuration) --no-restore --output $(Build.ArtifactStagingDirectory)"

    #Archive Files
    - task: PublishBuildArtifacts@1
      displayName: "publish artifacts"
      inputs:
        ArtifactName: dot-net-demo-project

